version: "2"

services:
  db:
    image: mysql:5.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "discov001"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "catalog"
    ports:
      - "3306:3306"

  es:
    image: elasticsearch:1.5.2
    container_name: es
    volumes:
      - /tmp/elasticsearch/data:/es-data
    ports:
      - "9200:9200"
      - "9300:9300"

  memcache:
    image: memcached:1.4.24
    container_name: memcache

  course-catalog:
    # Uncomment this line to use the official course-catalog base image
    image: edxops/course-catalog:latest

    # Uncomment the next two lines to build from a local configuration repo
    #build: ../configuration
    #dockerfile: docker/build/catalog/Dockerfile

    container_name: course-catalog
    volumes:
      - .:/edx/app/catalog/catalog
    command: /edx/app/catalog/devstack.sh start
    depends_on:
      - "db"
      - "es"
      - "memcache"
    environment:
      TEST_ELASTICSEARCH_URL: "http://es:9200"
    ports:
      - "18381:18381"
      - "8381:8381"
      - "48381:48381"
